// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: halo/aggregator/v1/genesis.proto

package aggregator

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Owner       string                `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	LastRoundId uint64                `protobuf:"varint,2,opt,name=last_round_id,json=lastRoundId,proto3" json:"last_round_id,omitempty"`
	NextPrice   cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=next_price,json=nextPrice,proto3,customtype=cosmossdk.io/math.Int" json:"next_price"`
	Rounds      map[uint64]RoundData  `protobuf:"bytes,4,rep,name=rounds,proto3" json:"rounds" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3882f0774280089a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GenesisState) GetLastRoundId() uint64 {
	if m != nil {
		return m.LastRoundId
	}
	return 0
}

func (m *GenesisState) GetRounds() map[uint64]RoundData {
	if m != nil {
		return m.Rounds
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "halo.aggregator.v1.GenesisState")
	proto.RegisterMapType((map[uint64]RoundData)(nil), "halo.aggregator.v1.GenesisState.RoundsEntry")
}

func init() { proto.RegisterFile("halo/aggregator/v1/genesis.proto", fileDescriptor_3882f0774280089a) }

var fileDescriptor_3882f0774280089a = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x8a, 0x13, 0x31,
	0x18, 0xc7, 0x27, 0xed, 0xec, 0xc2, 0x66, 0x14, 0x34, 0xac, 0x30, 0x16, 0x9c, 0x1d, 0xd6, 0x4b,
	0x11, 0x9b, 0xb8, 0xbb, 0x1e, 0xc4, 0x9b, 0x45, 0x91, 0x7a, 0x50, 0x99, 0xbd, 0x88, 0x97, 0x21,
	0xed, 0x84, 0x74, 0xd8, 0x99, 0xa4, 0x24, 0x69, 0xdd, 0xbe, 0x85, 0x8f, 0xe1, 0xd1, 0xc3, 0x3e,
	0xc4, 0x1e, 0x4b, 0x4f, 0xea, 0xa1, 0x48, 0x7b, 0xf0, 0x35, 0x24, 0xc9, 0x80, 0x03, 0xf6, 0x32,
	0x93, 0xfc, 0xbf, 0x3f, 0xff, 0xdf, 0xf7, 0xe5, 0x83, 0xe9, 0x94, 0x56, 0x92, 0x50, 0xce, 0x15,
	0xe3, 0xd4, 0x48, 0x45, 0x16, 0x67, 0x84, 0x33, 0xc1, 0x74, 0xa9, 0xf1, 0x4c, 0x49, 0x23, 0x11,
	0xb2, 0x0e, 0xfc, 0xcf, 0x81, 0x17, 0x67, 0xbd, 0xfb, 0xb4, 0x2e, 0x85, 0x24, 0xee, 0xeb, 0x6d,
	0xbd, 0x87, 0x13, 0xa9, 0x6b, 0xa9, 0x73, 0x77, 0x23, 0xfe, 0xd2, 0x94, 0x8e, 0xb9, 0xe4, 0xd2,
	0xeb, 0xf6, 0xd4, 0xa8, 0x8f, 0xf7, 0x90, 0x5b, 0x14, 0x67, 0x3a, 0xfd, 0xd9, 0x81, 0x77, 0xde,
	0xfa, 0x76, 0x2e, 0x0d, 0x35, 0x0c, 0x61, 0x78, 0x20, 0xbf, 0x08, 0xa6, 0x62, 0x90, 0x82, 0xfe,
	0xd1, 0x30, 0x5e, 0xdf, 0x0c, 0x8e, 0x1b, 0xd8, 0xab, 0xa2, 0x50, 0x4c, 0xeb, 0x4b, 0xa3, 0x4a,
	0xc1, 0x33, 0x6f, 0x43, 0xa7, 0xf0, 0x6e, 0x45, 0xb5, 0xc9, 0x95, 0x9c, 0x8b, 0x22, 0x2f, 0x8b,
	0xb8, 0x93, 0x82, 0x7e, 0x98, 0x45, 0x56, 0xcc, 0xac, 0x36, 0x2a, 0xd0, 0x07, 0x08, 0x05, 0xbb,
	0x36, 0xf9, 0x4c, 0x95, 0x13, 0x16, 0x77, 0x5d, 0xf0, 0xb3, 0xdb, 0xcd, 0x49, 0xf0, 0x6b, 0x73,
	0xf2, 0xc0, 0x87, 0xeb, 0xe2, 0x0a, 0x97, 0x92, 0xd4, 0xd4, 0x4c, 0xf1, 0x48, 0x98, 0xf5, 0xcd,
	0x00, 0x36, 0xd4, 0x91, 0x30, 0xdf, 0xfe, 0x7c, 0x7f, 0x02, 0xb2, 0x23, 0x9b, 0xf1, 0xd1, 0x46,
	0xa0, 0x77, 0xf0, 0xd0, 0xf1, 0x74, 0x1c, 0xa6, 0xdd, 0x7e, 0x74, 0xfe, 0x14, 0xff, 0xff, 0x86,
	0xb8, 0x3d, 0x16, 0x76, 0xad, 0xe8, 0x37, 0xc2, 0xa8, 0xe5, 0x30, 0xb4, 0xe8, 0xac, 0x49, 0xe8,
	0x7d, 0x82, 0x51, 0xab, 0x88, 0xee, 0xc1, 0xee, 0x15, 0x5b, 0xba, 0xe9, 0xc3, 0xcc, 0x1e, 0xd1,
	0x05, 0x3c, 0x58, 0xd0, 0x6a, 0xce, 0xdc, 0x64, 0xd1, 0xf9, 0xa3, 0x7d, 0x2c, 0x97, 0xf0, 0x9a,
	0x1a, 0x9a, 0x79, 0xef, 0xcb, 0xce, 0x0b, 0x30, 0x7c, 0x7f, 0xbb, 0x4d, 0xc0, 0x6a, 0x9b, 0x80,
	0xdf, 0xdb, 0x04, 0x7c, 0xdd, 0x25, 0xc1, 0x6a, 0x97, 0x04, 0x3f, 0x76, 0x49, 0xf0, 0xf9, 0x39,
	0x2f, 0xcd, 0x74, 0x3e, 0xc6, 0x13, 0x59, 0x13, 0x21, 0xc7, 0x15, 0x1b, 0x50, 0xad, 0x99, 0xd1,
	0xc4, 0xad, 0xec, 0xda, 0xff, 0xcc, 0x72, 0xc6, 0x74, 0x6b, 0x63, 0xe3, 0x43, 0xb7, 0xb2, 0x8b,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0x9d, 0x4b, 0x01, 0x53, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rounds) > 0 {
		for k := range m.Rounds {
			v := m.Rounds[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i = encodeVarintGenesis(dAtA, i, uint64(k))
			i--
			dAtA[i] = 0x8
			i = encodeVarintGenesis(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.NextPrice.Size()
		i -= size
		if _, err := m.NextPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.LastRoundId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LastRoundId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.LastRoundId != 0 {
		n += 1 + sovGenesis(uint64(m.LastRoundId))
	}
	l = m.NextPrice.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Rounds) > 0 {
		for k, v := range m.Rounds {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + sovGenesis(uint64(k)) + 1 + l + sovGenesis(uint64(l))
			n += mapEntrySize + 1 + sovGenesis(uint64(mapEntrySize))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastRoundId", wireType)
			}
			m.LastRoundId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastRoundId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NextPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rounds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Rounds == nil {
				m.Rounds = make(map[uint64]RoundData)
			}
			var mapkey uint64
			mapvalue := &RoundData{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowGenesis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowGenesis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthGenesis
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthGenesis
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &RoundData{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipGenesis(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthGenesis
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Rounds[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
