// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: halo/aggregator/v1/query.proto

package aggregatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Owner_FullMethodName              = "/halo.aggregator.v1.Query/Owner"
	Query_NextPrice_FullMethodName          = "/halo.aggregator.v1.Query/NextPrice"
	Query_RoundData_FullMethodName          = "/halo.aggregator.v1.Query/RoundData"
	Query_LatestRoundData_FullMethodName    = "/halo.aggregator.v1.Query/LatestRoundData"
	Query_RoundDetails_FullMethodName       = "/halo.aggregator.v1.Query/RoundDetails"
	Query_LatestRoundDetails_FullMethodName = "/halo.aggregator.v1.Query/LatestRoundDetails"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	Owner(ctx context.Context, in *QueryOwner, opts ...grpc.CallOption) (*QueryOwnerResponse, error)
	NextPrice(ctx context.Context, in *QueryNextPrice, opts ...grpc.CallOption) (*QueryNextPriceResponse, error)
	RoundData(ctx context.Context, in *QueryRoundData, opts ...grpc.CallOption) (*QueryRoundDataResponse, error)
	LatestRoundData(ctx context.Context, in *QueryLatestRoundData, opts ...grpc.CallOption) (*QueryRoundDataResponse, error)
	RoundDetails(ctx context.Context, in *QueryRoundDetails, opts ...grpc.CallOption) (*QueryRoundDetailsResponse, error)
	LatestRoundDetails(ctx context.Context, in *QueryLatestRoundDetails, opts ...grpc.CallOption) (*QueryRoundDetailsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Owner(ctx context.Context, in *QueryOwner, opts ...grpc.CallOption) (*QueryOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryOwnerResponse)
	err := c.cc.Invoke(ctx, Query_Owner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NextPrice(ctx context.Context, in *QueryNextPrice, opts ...grpc.CallOption) (*QueryNextPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryNextPriceResponse)
	err := c.cc.Invoke(ctx, Query_NextPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RoundData(ctx context.Context, in *QueryRoundData, opts ...grpc.CallOption) (*QueryRoundDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoundDataResponse)
	err := c.cc.Invoke(ctx, Query_RoundData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestRoundData(ctx context.Context, in *QueryLatestRoundData, opts ...grpc.CallOption) (*QueryRoundDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoundDataResponse)
	err := c.cc.Invoke(ctx, Query_LatestRoundData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RoundDetails(ctx context.Context, in *QueryRoundDetails, opts ...grpc.CallOption) (*QueryRoundDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoundDetailsResponse)
	err := c.cc.Invoke(ctx, Query_RoundDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestRoundDetails(ctx context.Context, in *QueryLatestRoundDetails, opts ...grpc.CallOption) (*QueryRoundDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRoundDetailsResponse)
	err := c.cc.Invoke(ctx, Query_LatestRoundDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	Owner(context.Context, *QueryOwner) (*QueryOwnerResponse, error)
	NextPrice(context.Context, *QueryNextPrice) (*QueryNextPriceResponse, error)
	RoundData(context.Context, *QueryRoundData) (*QueryRoundDataResponse, error)
	LatestRoundData(context.Context, *QueryLatestRoundData) (*QueryRoundDataResponse, error)
	RoundDetails(context.Context, *QueryRoundDetails) (*QueryRoundDetailsResponse, error)
	LatestRoundDetails(context.Context, *QueryLatestRoundDetails) (*QueryRoundDetailsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Owner(context.Context, *QueryOwner) (*QueryOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Owner not implemented")
}
func (UnimplementedQueryServer) NextPrice(context.Context, *QueryNextPrice) (*QueryNextPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextPrice not implemented")
}
func (UnimplementedQueryServer) RoundData(context.Context, *QueryRoundData) (*QueryRoundDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoundData not implemented")
}
func (UnimplementedQueryServer) LatestRoundData(context.Context, *QueryLatestRoundData) (*QueryRoundDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestRoundData not implemented")
}
func (UnimplementedQueryServer) RoundDetails(context.Context, *QueryRoundDetails) (*QueryRoundDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoundDetails not implemented")
}
func (UnimplementedQueryServer) LatestRoundDetails(context.Context, *QueryLatestRoundDetails) (*QueryRoundDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestRoundDetails not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Owner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOwner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Owner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Owner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Owner(ctx, req.(*QueryOwner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NextPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNextPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NextPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_NextPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NextPrice(ctx, req.(*QueryNextPrice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RoundData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRoundData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RoundData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_RoundData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RoundData(ctx, req.(*QueryRoundData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestRoundData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestRoundData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestRoundData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LatestRoundData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestRoundData(ctx, req.(*QueryLatestRoundData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RoundDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRoundDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RoundDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_RoundDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RoundDetails(ctx, req.(*QueryRoundDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestRoundDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestRoundDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestRoundDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LatestRoundDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestRoundDetails(ctx, req.(*QueryLatestRoundDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "halo.aggregator.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Owner",
			Handler:    _Query_Owner_Handler,
		},
		{
			MethodName: "NextPrice",
			Handler:    _Query_NextPrice_Handler,
		},
		{
			MethodName: "RoundData",
			Handler:    _Query_RoundData_Handler,
		},
		{
			MethodName: "LatestRoundData",
			Handler:    _Query_LatestRoundData_Handler,
		},
		{
			MethodName: "RoundDetails",
			Handler:    _Query_RoundDetails_Handler,
		},
		{
			MethodName: "LatestRoundDetails",
			Handler:    _Query_LatestRoundDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "halo/aggregator/v1/query.proto",
}
